<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a64c5d69-583c-4d19-894d-3f73666321b7</elementGuidId>
    <imagePath></imagePath>
    <name>input_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#text</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'text') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh</value>
        <webElementGuid>85a02e1e-03d4-4dba-bd9f-c86c0b2f1c49</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>18c49c9e-b49d-4d96-95c7-cc17ea61917f</webElementGuid>
    </webElementProperties>
</WebElementEntity>