<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d47ced14-5df3-4e15-b0dd-c877a015cefa</elementGuidId>
    <imagePath></imagePath>
    <name>input_address</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#address</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'address') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh</value>
        <webElementGuid>22a4df6b-007e-4185-873e-c4cb99bfe8fe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>address</value>
        <webElementGuid>4473a44d-9d32-4112-8ca0-5b1d00ad3810</webElementGuid>
    </webElementProperties>
</WebElementEntity>